#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=2.1.5
PACKAGE=abyss
TOOL=abyss-pe
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

PERSISTENT_FILESYSTEM=/ocean
if [ ! -d $PERSISTENT_FILESYSTEM ]; then
	singularity exec $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
else
	singularity exec -B $PERSISTENT_FILESYSTEM $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
fi
