#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=2.1.5
PACKAGE=abyss
TOOL=abyss-pe
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

singularity exec -B /ocean $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
